core/urls.py
from django.urls import path
from . import views
from .views import *


urlpatterns = [
	path('', views.index, name='index'),
	path('news/', views.news, name='news'),
	path('post/<post_id>', views.post, name='post'),
	path('add_comment/<post_id>', views.add_comment, name='add-comment'),
	path('post/<post_id>/reply/<comment_id>', views.reply, name = 'reply'),
	path('faq/', views.faq, name='faq'),
	path('faq-single/<faq_id>',views.faq_single, name='faq-single'),
	path('contact/', views.contact, name = 'contact'),
	path('search/', views.search, name='search'),
	path('create/', views.create, name='create'),
	path('edit/<post_id>', views.edit, name = 'edit'),
	path('delete/<post_id>', views.delete, name = 'delete')
	
]

app_name = 'core'

cryptoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include('core.urls',namespace = 'core')),
    path('subscribe/', include('subscribe.urls',namespace = 'subscribe'))
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

subscribe/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.subscribe, name='sub')
	
]


app_name = 'subscribe'

core/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

CATEGORIES = (
	('CM','Crypto Mining'),
	('S','Stock'),
	('M','Market'),
	('O','Other'),
)

# Create your models here.
class Author(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	profile_picture = models.ImageField(upload_to = 'static/core/profile_pictures',null = True)
	
	def __str__(self):
		return str(self.user)


class Post(models.Model):
	title = models.CharField(max_length = 100)
	overview = models.TextField()
	text = models.TextField()
	featured = models.BooleanField(default = False)
	author = models.ForeignKey(Author, on_delete = models.CASCADE)
	category = models.CharField(choices = CATEGORIES,max_length = 2, default='O')
	thumbnail = models.ImageField(upload_to = 'static/core/thumbnails',null = True)
	views = models.IntegerField(default = 0)
	comments = models.IntegerField(default = 0)
	timestamp = models.DateTimeField()
	
	def __str__(self):
		return self.title

class Comment(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
	post = models.ForeignKey(Post, on_delete = models.CASCADE, null = True)
	text = models.TextField()
	replies = models.ManyToManyField("Reply")
	
	def __str__(self):
		return self.text[:25] + '...'
		

class Reply(models.Model):
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	comment_on = models.ForeignKey(Comment, on_delete = models.CASCADE)
	post = models.ForeignKey(Post, on_delete = models.CASCADE, null = True)
	text = models.TextField()
	
	def __str__(self):
		return self.text[:25] + '...'

class FAQ(models.Model):
	title = models.CharField(max_length = 200)
	text = models.TextField()
	
	def __str__(self):
		return self.title

core/forms.py
from django import forms
from .models import *

from tinymce import TinyMCE

class TinyMCEWidget(TinyMCE):
	def use_required_attribute(self, *args):
		return False
		

class PostForm(forms.ModelForm):
	text = forms.CharField(widget = TinyMCEWidget(attrs = {'required':False, 'cols':30, 'rows': 10}))
	overview = forms.CharField(widget = TinyMCEWidget(attrs = {'required':False, 'cols':30, 'rows': 10}))
	
	class Meta:
		model = Post
		fields = ['title','overview','text','featured','category','thumbnail']

core/views.py
from django.shortcuts import render
from .models import *
from subscribe.models import *
from .forms import *
from django.core.mail import send_mail
from .forms import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def get_author(user):
	qs = Author.objects.filter(user = user)
	if qs:
		return qs[0]	
	return None


def index(request):
	featured_posts = Post.objects.filter(featured = True).order_by('id')
	
	recent_posts = Post.objects.order_by('-timestamp')
	
	crypto_posts = Post.objects.filter(category = 'CM')[:4]
	
	popular_posts = Post.objects.order_by('-views')[:4]
	
		
	context = {'featured_posts':featured_posts,
				'recent_posts':recent_posts,
				'crypto_posts':crypto_posts,
				'popular_posts':popular_posts}
	
	return render(request, 'core/index.html',context)
	
def post(request,post_id):
	popular_posts = Post.objects.order_by('-views')[:4]
	try:
		post = Post.objects.get(id = post_id)
		previous_post = Post.objects.filter(timestamp__lte = post.timestamp).exclude(id = post_id).order_by('-timestamp').first()
		next_post = Post.objects.filter(timestamp__gte = post.timestamp).exclude(id = post_id).order_by('timestamp').first()
		comments = Comment.objects.filter(post = post)	
		context = {'post':post,
				'popular_posts':popular_posts,
				'previous_post':previous_post,
				'next_post':next_post,
				'comments':comments}
	except ObjectDoesNotExist:
		return HttpResponseRedirect(reverse('core:index'))
		
	return render(request, 'core/03_single-post.html',context)
	
@login_required	
def add_comment(request,post_id):
	post = Post.objects.get(id = post_id)
	
	if request.method == 'POST':
		comment = request.POST.get('comment')
		new_comment = Comment()
		new_comment.text = comment
		new_comment.user = request.user
		new_comment.post = post
		new_comment.save()
		post.comments += 1
		post.save()
		return HttpResponseRedirect(reverse('core:post', args=[post.id]))
		
	context = {'post':post}
	return render(request, 'core/03_single-post.html', context)

@login_required	
def reply(request, post_id, comment_id):
	comment = Comment.objects.get(id = comment_id)
	post = Post.objects.get(id = post_id)
	if request.method == 'POST':
		reply_text = request.POST.get('reply')
		new_reply = Reply()
		new_reply.user = request.user
		new_reply.comment_on = comment
		new_reply.post = post
		new_reply.text = reply_text
		new_reply.save()
		comment.replies.add(new_reply)
		comment.save()
		post.comments += 1
		post.save()
		return HttpResponseRedirect(reverse('core:post',args=[post.id]))
	context = {'comment':comment,'post':post}
	return render(request, 'core/03_single-post.html',context)
	
def faq(request):
	faqs = FAQ.objects.all()
	
	context = {'faqs':faqs}
	return render(request, 'core/04_FAQs.html',context)
	
def faq_single(request, faq_id):
	faq = FAQ.objects.get(id = faq_id)
	
	context = {'faq':faq}
	return render(request, 'core/05_FAQs-single.html',context)

	
def contact(request):
	
	if request.method == 'POST':
		full_name = request.POST.get('full-name')
		subject = 'Email from ' + str(full_name) 
		email = request.POST.get('email')
		message = request.POST.get('message')
		send_mail(
				subject,
				str(message),
				str(email),
				['vuk.tsa.mes@gmail.com'],
				fail_silently=False)
		
	
	return render(request, 'core/06_contact-us.html')
	
def news(request):
	posts = Post.objects.all()
	popular_posts = Post.objects.order_by('-views')[:4]
	paginator = Paginator(posts, 4)
	
	try:
		page_number = request.GET.get('page')
		page_obj = paginator.get_page(page_number)
	except EmptyPage:
		page_obj = paginator.get_page(num_pages)
	except PageNotAnInteger:
		page_obj = paginator.get_page(1)
	
	context = {'posts':posts,
				'popular_posts':popular_posts,
				'page_obj':page_obj}
				
	return render(request, 'core/02_archive-page.html', context)
	
	
def search(request):
	posts = Post.objects.all()
	query = request.GET.get('query')
	popular_posts = Post.objects.order_by('-views')[:4]
	
	if query:
		posts = Post.objects.filter(Q(title__icontains = query) | Q(overview__icontains = query) | Q(text__icontains = query))
		
	context = {'posts':posts,
				'popular_posts':popular_posts}
				
	return render(request, 'core/search.html',context)
	
@staff_member_required	
def create(request):
	form = PostForm(request.POST, request.FILES)
	author = get_author(request.user)
	if request.method == 'POST':
		if form.is_valid():
			new_post = form.save(commit = False)
			new_post.author = author
			new_post.timestamp = timezone.now()
			new_post.save()
			return HttpResponseRedirect(reverse('core:news'))
	
	context = {'form':form}
	return render(request, 'core/create.html',context)
	
@staff_member_required		
def edit(request, post_id):
	post  = Post.objects.get(id = post_id)
	form = PostForm(instance = post)
	
	if request.method == 'POST':
		form = PostForm(request.POST,request.FILES, instance = post)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('core:post', args=[post.id]))
	context = {'form':form, 'post':post}
	return render(request, 'core/edit.html',context)

@staff_member_required	
def delete(request, post_id):
	post = Post.objects.get(id = post_id)
	post.delete()
	return HttpResponseRedirect(reverse('core:news'))
	
	

core/templates/core/02_archive-page.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
	<section class="ptb-0">
		<div class="mb-30 brdr-ash-1 opacty-5"></div>
		<div class="container">
			<a class="mt-10" href="/"><i class="mr-5 ion-ios-home"></i>Home<i class="mlr-10 ion-chevron-right"></i></a>
			<a class="mt-10 color-ash" href="/news">News</a>
		</div><!-- container -->
	</section>
	
	<section>
		<div class="container">
			<div class="row">
			
				<div class="col-md-12 col-lg-8">
					</br>
					</br>
					<h4 class="p-title"><b>ALL POSTS</b></h4>
					<div class="row">
						
						{% for post in page_obj %}
						<div class="col-sm-6">
							<img src="{{ post.thumbnail.url }}" alt="">
							<h4 class="pt-20"><a href="{% url 'core:post' post.id %}"><b>{{ post.title }}</b></a></h4>
							<ul class="list-li-mr-20 pt-10 mb-30">
								<li class="color-lite-black">by <b>{{ post.author }}</b></a>
								{{ post.timestamp|timesince }}</li>
								<li><i class="color-primary mr-5 font-12 ion-ios-bolt"></i>{{ post.comments }}</li>
								<li><i class="color-primary mr-5 font-12 ion-chatbubbles"></i>{{ post.views }}</li>
							</ul>
						</div><!-- col-sm-6 -->
						{% endfor %}
						
					</div><!-- row -->
					
					{% if page_obj.has_previous %}
					<a class="dplay-block btn-brdr-primary mt-20 mb-md-50" href="?page={{ page_obj.previous_page_number }}"><b>GO BACK</b></a>
					{% endif %}					
					{% if page_obj.has_next %}
					<a class="dplay-block btn-brdr-primary mt-20 mb-md-50" href="?page={{ page_obj.next_page_number }}"><b>LOAD MORE</b></a>
					{% endif %}
				</div><!-- col-md-9 -->
				
				<div class="d-none d-md-block d-lg-none col-md-3"></div>
				<div class="col-md-6 col-lg-4">
					<div class="pl-20 pl-md-0">
						
						<div class="mtb-50">
							<h4 class="p-title"><b>POPULAR POSTS</b></h4>
							{% for popular_post in popular_posts %}
							<a class="oflow-hidden pos-relative mb-20 dplay-block" href="{% url 'core:post' popular_post.id %}">
								<div class="wh-100x abs-tlr"><img src="{{ popular_post.thumbnail.url }}" alt=""></div>
								<div class="ml-120 min-h-100x">
									<h5><b>{{ popular_post.title }}</b></h5>
									<h6 class="color-lite-black pt-10">by <span class="color-black"><b>{{ popular_post.author }},</b></span> {{ popular_post.timestamp }}</h6>
								</div>
							</a><!-- oflow-hidden -->
							{% endfor %}
							
						</div><!-- mtb-50 -->
						
						
						<div class="mtb-50 mb-md-0">
							<h4 class="p-title"><b>NEWSLETTER</b></h4>
							<p class="mb-20">Subscribe to our newsletter to get notification about new updates,
								information, discount, etc..</p>
							<form class="nwsltr-primary-1" action="{% url 'subscribe:sub' %}" method="post">
								{% csrf_token %}
								<input type="text" name='email' placeholder="Your email"/>
								<button type="submit"><i class="ion-ios-paperplane"></i></button>
							</form>
						</div><!-- mtb-50 -->
						
					</div><!--  pl-20 -->
				</div><!-- col-md-3 -->
				
			</div><!-- row -->
		</div><!-- container -->
	</section>
{% endblock content %}

core/templates/core/03_single-post.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
	<section class="ptb-0">
		<div class="mb-30 brdr-ash-1 opacty-5"></div>
		<div class="container">
			<a class="mt-10" href="/"><i class="mr-5 ion-ios-home"></i>Home<i class="mlr-10 ion-chevron-right"></i></a>
			<a class="mt-10" href="/news">News<i class="mlr-10 ion-chevron-right"></i></a>
			<a class="mt-10 color-ash" href="{% url 'core:post' post.id %}">{{ post.title }}</a>
		</div><!-- container -->
	</section>
	
	
	<section>
		<div class="container">
			<div class="row">
			
				<div class="col-md-12 col-lg-8">
					<img src="{{ post.thumbnail.url }}" alt="">
					<h3 class="mt-30"><b>{{ post.title }}</b></h3>
					<ul class="list-li-mr-20 mtb-15">
						<li>by <a href="#"><b>{{ post.author }}</b></a> {{ post.timestamp|timesince }}</li>
						<li><i class="color-primary mr-5 font-12 ion-ios-bolt"></i>{{ post.views }}</li>
						<li><i class="color-primary mr-5 font-12 ion-chatbubbles"></i>{{ post.comments }}</li>
					</ul>
					
					{{ post.text|safe }}
					
					<div class="float-left-right text-center mt-40 mt-sm-20">
				
						<ul class="mb-30 list-li-mt-10 list-li-mr-5 list-a-plr-15 list-a-ptb-7 list-a-bg-grey list-a-br-2 list-a-hvr-primary ">
							<li><a>{{ post.get_category_display }}</a></li>
						</ul>
						{% if request.user.is_staff %}
						<ul class="mb-30 list-a-hvr-primary list-li-ml-5">
							<li><a href="{% url 'core:edit' post.id %}">Edit</a></li>
							<li><a href="{% url 'core:delete' post.id %}">Delete</a></li>
						</ul>
						{% endif %}
						
					</div><!-- float-left-right -->
				
					<div class="brdr-ash-1 opacty-5"></div>
					
					<h4 class="p-title mt-50"><b>YOU MAY ALSO LIKE</b></h4>
					<div class="row">
						{% if previous_post %}
						<div class="col-sm-6">
							<img src="{{ previous_post.thumbnail.url }}" alt="">
							<h4 class="pt-20"><a href="{% url 'core:post' previous_post.id %}">{{ previous_post.title }}</a></h4>
							<ul class="list-li-mr-20 pt-10 mb-30">
								<li class="color-lite-black">by <a href="{% url 'core:post' previous_post.id %}" class="color-black"><b>{{ previous_post.author }},</b></a>
								{{ previous_post.timestamp|timesince }}</li>
								<li><i class="color-primary mr-5 font-12 ion-ios-bolt"></i>{{ previous_post.views }}</li>
								<li><i class="color-primary mr-5 font-12 ion-chatbubbles"></i>{{ previous_post.comments }}</li>
							</ul>
						</div><!-- col-sm-6 -->
						{% endif %}
						
						{% if next_post %}
						<div class="col-sm-6">
							<img src="{{ next_post.thumbnail.url }}" alt="">
							<h4 class="pt-20"><a href="{% url 'core:post' next_post.id %}">{{ next_post.title }}</h4>
							<ul class="list-li-mr-20 pt-10 mb-30">
								<li class="color-lite-black">by <a href="{% url 'core:post' next_post.id %}" class="color-black"><b>{{ next_post.author }},</b></a>
								{{ next_post.timestamp|timesince }}</li>
								<li><i class="color-primary mr-5 font-12 ion-ios-bolt"></i>{{ next_post.views }}</li>
								<li><i class="color-primary mr-5 font-12 ion-chatbubbles"></i>{{ next_post.comments }}</li>
							</ul>
						</div><!-- col-sm-6 -->
						{% else %}
						
						{% endif %}
						
					</div><!-- row -->
					
					<h4 class="p-title mt-20"><b>{{ post.comments }} COMMENTS</b></h4>
					{% for comment in comments %}
					<div class="sided-70 mb-40">
						{% if comment.user.is_staff %}
						<div class="s-left rounded">
							<img src="{{ post.author.profile_picture.url }}" alt="">
						</div><!-- s-left -->
						{% else %}
						<div class="s-left rounded">
							<img src="{% static 'core/images/download.jpg' %}" alt="">
						</div><!-- s-left -->						
						{% endif %}
						
						<div class="s-right ml-100 ml-xs-85">
							<h5><b>{{ comment.user.username }} </b></h5>
							<p class="mtb-15">{{ comment.text }}</p>					
						</div><!-- s-right -->
					</div><!-- sided-70 -->
						{% for reply in comment.replies.all  %}
						<div class="sided-70 ml-100 ml-xs-20 mb-40">
						
						{% if comment.user == post.author.user %}
						<div class="s-left rounded">
							<img src="{{ post.author.profile_picture.url }}" alt="">
						</div><!-- s-left -->
						{% else %}
						<div class="s-left rounded">
							<img src="{% static 'core/images/download.jpg' %}" alt="">
						</div><!-- s-left -->						
						{% endif %}
						<div class="s-right ml-100 ml-xs-85">
							<h5><b>{{ reply.user.username }}</b></h5>
							<p class="mtb-10">{{ reply.text }}</p>
						</div><!-- s-right -->
					</div>
						{% endfor %}
					<div class="sided-70 ml-100 ml-xs-20 mb-40">		
							<form class="form-block form-plr-15 form-h-45 form-mb-20 form-brdr-lite-white mb-md-50" action="{% url 'core:reply' post.id  comment.id %}" method = 'post'>
							{% csrf_token %}
							<textarea class="ptb-10" name='reply' placeholder="Leave reply" required></textarea>
							<button class="btn-brdr-grey btn-b-sm plr-15 mr-10 mt-5" type="submit"><b>REPLY</b></button>
							<input type='hidden' name='next' value="." />
							</form>	
					</div>												
					{% endfor %}
					
					
					<h4 class="p-title mt-20"><b>LEAVE A COMMENT</b></h4>
					
					<form class="form-block form-plr-15 form-h-45 form-mb-20 form-brdr-lite-white mb-md-50" action="{% url 'core:add-comment' post.id %}" method = 'post'>
						{% csrf_token %}
						<textarea class="ptb-10" name='comment' placeholder="Your Comment" required></textarea>
						<button class="btn-fill-primary plr-30" rows="4" cols="50" type="submit"><b>LEAVE A COMMENT</b></button>
					</form>
				</div><!-- col-md-9 -->
				
				<div class="d-none d-md-block d-lg-none col-md-3"></div>
				<div class="col-md-6 col-lg-4">
					<div class="pl-20 pl-md-0">
						<ul class="list-block list-li-ptb-15 list-btm-border-white bg-primary text-center">
							<li><b>1 BTC = $13,2323</b></li>
							<li><b>1 BCH = $924</b></li>
							<li><b>1 ETH = $1,232</b></li>
							<li><b>1 LTC = $5611</b></li>
							<li><b>1 DAS = $1,002</b></li>
							<li><b>1 BCC = $99</b></li>
						</ul>
						
						<div class="mtb-50">
							<h4 class="p-title"><b>POPULAR POSTS</b></h4>
							
							{% for post in popular_posts %}
							<a class="oflow-hidden pos-relative mb-20 dplay-block" href="{% url 'core:post' post.id %}">
								<div class="wh-100x abs-tlr"><img src="{{ post.thumbnail.url }}" alt=""></div>
								<div class="ml-120 min-h-100x">
									<h5><b>{{ post.title }}</b></h5>
									<h6 class="color-lite-black pt-10">by <span class="color-black"><b>{{ post.author }},</b></span> {{ post.timestamp|timesince }}</h6>
								</div>
							</a><!-- oflow-hidden -->
							{% endfor %}
							
						</div><!-- mtb-50 -->
						
						<div class="mtb-50 mb-md-0">
							<h4 class="p-title"><b>NEWSLETTER</b></h4>
							<p class="mb-20">Subscribe to our newsletter to get notification about new updates,
								information, discount, etc..</p>
							<form class="nwsltr-primary-1" action="{% url 'subscribe:sub' %}" method='post'>
								{% csrf_token %}
								<input type="email" name='email' placeholder="Your email"/>
								<button type="submit"><i class="ion-ios-paperplane"></i></button>
							</form>
						</div><!-- mtb-50 -->
						
					</div><!--  pl-20 -->
				</div><!-- col-md-3 -->
				
			</div><!-- row -->
			
		</div><!-- container -->
	</section>
{% endblock content %}

core/templates/core/04_FAQs.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
	<section class="ptb-0">
		<div class="mb-30 brdr-ash-1 opacty-5"></div>
		<div class="container">
			<a class="mt-10" href="index.html"><i class="mr-5 ion-ios-home"></i>Home<i class="mlr-10 ion-chevron-right"></i></a>
			<a class="mt-10 color-ash" href="04_FAQs.html">FAQs</a>
		</div><!-- container -->
	</section>
	
	
	<section class="pb-20">
		<div class="container">
			<h2 class="mb-50"><b>FAQs</b></h2>

		</div><!-- container -->
	</section>
	
	<section class="pt-0">
		<div class="container">
			
			{% for faq in faqs %}
			<div class="accordian">
				<h5><a data-accordian="#accordian-{{ forloop.counter }}" class="a-title" href="#">
					<b>{{ faq.title }}</b><i class="ion-plus"></i></a></h5>
					
				<div class="a-body" id="accordian-{{ forloop.counter }}">
					<div class="a-body-inner">
						<p>{{ faq.text|slice:":100" }} ...</p>
						<a class="mt-15 link-brdr-btm-primary color-primary" href="{% url 'core:faq-single' faq.id %}"><b>Read more</b></a>	
					</div><!-- a-body-inner -->	
				</div><!-- a-body -->	
			</div><!-- accordian -->
			{% endfor %}
		
			
		</div><!-- container -->
	</section>
{% endblock content %}	
	

core/templates/core/05_FAQs-single.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
	<section class="ptb-0">
		<div class="mb-30 brdr-ash-1 opacty-5"></div>
		<div class="container">
			<a class="mt-10" href="index.html"><i class="mr-5 ion-ios-home"></i>Home<i class="mlr-10 ion-chevron-right"></i></a>
			<a class="mt-10" href="04_FAQs.html">FAQs<i class="mlr-10 ion-chevron-right"></i></a>
			<a class="color-ash mt-10" href="04_FAQs-single.html">{{ faq.title }}</a>
		</div><!-- container -->
	</section>
	
	
	<section>
		<div class="container">
			<h2 class="mb-50"><b>FAQs</b></h2>
			<h4><b>{{ faq.title }}</b></h4>
			
			<p class="pt-30">{{ faq.text }}</p>
						
		</div><!-- container -->
	</section>
	
{% endblock %}

core/templates/core/06_contact-us.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
	<section class="ptb-0">
		<div class="mb-30 brdr-ash-1 opacty-5"></div>
		<div class="container">
			<a class="mt-10" href="index.html"><i class="mr-5 ion-ios-home"></i>Home<i class="mlr-10 ion-chevron-right"></i></a>
			<a class="color-ash mt-10" href="06_contact-us.html">Contact us</a>
		</div><!-- container -->
	</section>
	
	
	<section>
		<div class="container">
			<div class="row">
			
				<div class="col-sm-12 col-md-8">
					<h3><b>SEND US A MESSAGE</b></h3>
					<p class="mb-30 mr-100 mr-sm-0">We’d love to hear from you – please get in touch for comments, requests, 
						advertising partnerships or job inquiries.</p>
					<form class="form-block form-bold form-mb-20 form-h-35 form-brdr-b-grey pr-50 pr-sm-0" action="{% url 'core:contact' %}" method='post'>
						{% csrf_token %}
						<div class="row">
						
							<div class="col-sm-6">
								<p class="color-ash">Full Name*</p>
								<div class="pos-relative">
									<input class="pr-20" type="text" name='full-name' value="Leonard">
									<i class="abs-tbr lh-35 font-13 color-green ion-android-done"></i>
								</div><!-- pos-relative -->
							</div><!-- col-sm-6 -->
							
							<div class="col-sm-6">							
								<p class="color-ash">Email*</p>
								<div class="pos-relative">
									<input class="pr-20" name='email' type="email">
									<i class="dplay-none abs-tbr lh-35 font-13 color-green ion-android-done"></i>
								</div><!-- pos-relative -->
							</div><!-- col-sm-6 -->
							
							
							<div class="col-sm-12">
								<div class="pos-relative pr-80">
									<p class="color-ash">Message*</p>
									<h4><b>Tell us about your question</b></h4>
									<textarea class="mb-0" name='message'></textarea>
									<button class="abs-br font-20 plr-15 btn-fill-primary" type="submit"><i class="ion-ios-paperplane"></i></button>
								</div><!-- pos-relative -->
							</div><!-- col-sm-6 -->
							
						</div><!-- row -->
					</form>
				</div><!-- col-md-6 -->
				
				<div class="col-sm-12 col-md-4">
					<h3 class="mb-20 mt-sm-50"><b>INFORMATION</b></h3>
					
					<ul class="font-11 list-relative list-li-pl-30 list-block list-li-mb-15">
						<li><i class="abs-tl ion-ios-location"></i>Your Address <br/>Your Address 2</li>
						<li><i class="abs-tl ion-android-mail"></i>youremail@gmail.com</li>
						<li><i class="abs-tl ion-android-call"></i>(+12)-345-678-910</li>
					</ul>
				
				</div><!-- col-md-6 -->
			</div><!-- row -->
		</div><!-- container -->
	</section>
{% endblock content %}

core/templates/core/create.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
</br>
<div class="container">
<div class="col-10 offset-1" >
	{{ form.media }}
	<form action="{% url 'core:create' %}" method='post' enctype='multipart/form-data' >
		{% csrf_token %}
		{{ form|crispy }}
		<button class ='btn btn-primary' type="submit">Create</button>
	</form>

</div>
</div>
</br>
</br>
</br>
</br>
</br>
</br>	

{% endblock content %}

core/templates/core/edit.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
</br>
<div class="container">
<div class="col-10 offset-1" >
	{{ form.media }}
	<form action="{% url 'core:edit' post.id %}" method='post' enctype='multipart/form-data' >
		{% csrf_token %}
		{{ form|crispy }}
		<button class ='btn btn-primary' type="submit">Edit</button>
	</form>

</div>
</div>
</br>
</br>
</br>
</br>
</br>
</br>	

{% endblock content %}